import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {chromium} from '/Users/rajan/Downloads/main portfolio/cinematic/node_modules/playwright/index.mjs';
const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const c=await b.newContext();const p=await c.newPage({viewport:{width:1440,height:1000}});const errors=[],failed=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)failed.push(r.url());});await p.goto('http://127.0.0.1:8091/',{waitUntil:'networkidle'});assert(await p.locator('#age-dialog').isVisible());await p.keyboard.press('Escape');assert(await p.locator('#age-dialog').isVisible());await p.click('#age-accept');await p.waitForTimeout(2200);assert(await p.locator('.page-loader').isHidden());await p.locator('#moods').scrollIntoViewIfNeeded();await p.waitForTimeout(450);assert.equal(await p.locator('.mood-product image[href]').count(),3);
for(const w of [1440,1024,768,390]){await p.setViewportSize({width:w,height:1000});await p.waitForTimeout(180);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),w);for(const s of ['.hero','.category-grid','.mood-grid','#hookah-products','#product-spotlight','.kit-grid','#accessory-products','.budget-cards','#arrival-products','.builder-layout','.guide-grid','#footer'])assert(await p.locator(s).isVisible(),s);}
await p.setViewportSize({width:1440,height:1000});await p.locator('#hookah-products').scrollIntoViewIfNeeded();await p.waitForTimeout(500);const rail=p.locator('#hookah-products');assert(await rail.evaluate(e=>e.scrollWidth>e.clientWidth));await p.locator('[data-rail="1"]').click();await p.waitForTimeout(600);assert(await rail.evaluate(e=>e.scrollLeft>0));await rail.evaluate(e=>e.scrollLeft=0);const r=await rail.boundingBox();await p.mouse.move(r.x+370,r.y+160);await p.mouse.down();await p.mouse.move(r.x+40,r.y+160,{steps:12});await p.mouse.up();assert(await rail.evaluate(e=>e.scrollLeft>40));assert(!(await p.locator('#content-dialog').isVisible()));await rail.evaluate(e=>e.scrollLeft=0);await p.locator('#hookah-products .product-card').first().hover();await p.locator('#hookah-products .quick-add').first().click();assert.equal(await p.locator('.bag-button .cart-count').innerText(),'1');assert(await p.locator('#hookah-products .quick-add').first().evaluate(e=>e.classList.contains('is-added')));assert(await p.locator('#toast').textContent().then(t=>t.includes('Added to your setup')));
await p.locator('[data-budget="under"]').click();assert.equal(await p.locator('#hookah-products .product-card').count(),1);await p.locator('[data-budget="all"]').click();await p.locator('#hookah-products .save-product').first().click();assert.equal(await p.locator('#hookah-products .save-product').first().getAttribute('aria-pressed'),'true');
await p.locator('.mood-party').click();assert.equal(await p.locator('#hookah-products .product-card').count(),2);await p.locator('[data-budget="all"]').click();
await p.selectOption('#setup-hookah','signature-chrome');await p.waitForTimeout(650);assert.equal(await p.locator('#setup-total').innerText(),'₹16,932');assert.equal(await p.locator('.vibe-meter').getAttribute('aria-valuenow'),'1');await p.selectOption('#setup-bowl','ceramic-duo');await p.waitForTimeout(650);assert.equal(await p.locator('.vibe-meter').getAttribute('aria-valuenow'),'2');await p.locator('#setup-form button[type="submit"]').click();assert.equal(await p.locator('.bag-button .cart-count').innerText(),'5');
await p.locator('#product-spotlight').scrollIntoViewIfNeeded();await p.waitForTimeout(600);assert.equal(await p.locator('.spotlight-choice').count(),4);for(const el of await p.locator('.budget-copy,#arrival-products .product-name').all())assert.equal(await el.evaluate(e=>getComputedStyle(e).opacity),'1');
await p.setViewportSize({width:390,height:844});await p.locator('.mobile-shop-bar button').click();assert(await p.locator('#shop-dialog').isVisible());await p.locator('#shop-dialog .close-dialog').click();await p.locator('.mobile-toggle').click();await p.locator('.mobile-category[data-nav-category="heat"]').click();assert.equal(await p.locator('#accessory-products .product-card').count(),1);assert(await p.locator('#mobile-nav').isHidden());
await p.emulateMedia({reducedMotion:'reduce'});await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>ScrollTrigger.getAll().length),0);assert(await p.locator('.page-loader').isHidden());assert(!(await p.evaluate(()=>document.body.classList.contains('has-studio-cursor'))));await p.emulateMedia({reducedMotion:'no-preference'});await p.waitForTimeout(300);assert(await p.evaluate(()=>ScrollTrigger.getAll().length>0));assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);const report={status:'passed',viewports:[1440,1024,768,390],checks:['age gate','loader ends','real mood visuals','carousel arrows and drag','quick add and bag count','wishlist','filters','count-up total','vibe meter','setup bundle','sharp card text','four-product spotlight','mobile shop bar','image mega menu','reduced-motion cleanup/restart'],errors,failed};await fs.writeFile('review/functional-results.json',JSON.stringify(report,null,2));console.log(report);await b.close();
