import {chromium} from '/Users/rajan/Downloads/main portfolio/cinematic/node_modules/playwright/index.mjs';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import AxeBuilder from '/tmp/urban-shisha-audits/node_modules/@axe-core/playwright/dist/index.mjs';
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();const errors=[],failed=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failed.push(r.url());});
await page.goto('http://127.0.0.1:8091/shop.html',{waitUntil:'networkidle'});assert.equal(await page.locator('#age-dialog').evaluate(e=>e.open),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#age-dialog').evaluate(e=>e.open),true);await page.click('#age-accept');await page.waitForTimeout(800);assert.equal(await page.locator('#shop-products .product-card').count(),12);
await page.check('[name="category"][value="hookahs"]');assert.equal(await page.locator('#shop-products .product-card').count(),4);
await page.check('[name="brand"][value="COCOYAYA"]');assert.equal(await page.locator('#shop-products .product-card').count(),3);
await page.selectOption('#shop-sort','price-low');assert.equal(await page.locator('#shop-products .product-card').first().getAttribute('data-id'),'studio-black');
await page.fill('#price-max','10000');await page.locator('#price-max').press('Tab');assert.equal(await page.locator('#shop-products .product-card').count(),1);
await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('#shop-products .product-card').count(),1);
await page.click('.shop-sidebar [data-clear]');assert.equal(await page.locator('#shop-products .product-card').count(),12);
await page.fill('#shop-search','NaGrani');await page.waitForTimeout(300);assert.equal(await page.locator('#shop-products .product-card').count(),1);await page.locator('#shop-products .add-product').click();assert.equal(await page.locator('.bag-button .cart-count').textContent(),'1');await page.locator('#shop-products .save-product').click();await page.locator('#shop-products .product-name').click();assert.equal(await page.locator('#content-title').textContent(),'NaGrani HMD');await page.keyboard.press('Escape');await page.click('[data-open="cart"]');await page.click('[data-quantity="heat-management"][data-delta="1"]');assert.equal(await page.locator('.bag-button .cart-count').textContent(),'2');await page.keyboard.press('Escape');
await page.goto('http://127.0.0.1:8091/');await page.waitForTimeout(1800);assert.equal(await page.locator('.bag-button .cart-count').textContent(),'2');await page.locator('#brands').scrollIntoViewIfNeeded();await page.waitForTimeout(400);assert.equal(await page.locator('.brand-tile').count(),6);assert.equal(await page.locator('.brand-logo img').evaluateAll(imgs=>imgs.every(i=>i.complete&&i.naturalWidth>0)),true);await page.screenshot({path:'review/home-brands-1440.png'});await page.locator('.brand-tile').first().click();assert.equal(await page.locator('#shop-empty').isVisible(),true);assert.match(await page.locator('#catalog-title').textContent(),/Al Fakher/);await page.locator('#shop-empty [data-clear]').click();assert.equal(await page.locator('#shop-products .product-card').count(),12);
const axe=[];for(const width of [1440,1024,768,390]){await page.setViewportSize({width,height:1000});await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(350);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);await page.screenshot({path:`review/shop-${width}.png`});const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();axe.push({width,violations:result.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}))});await page.locator('#shop-products').scrollIntoViewIfNeeded();await page.waitForTimeout(300);await page.screenshot({path:`review/shop-grid-${width}.png`});}
await page.click('#filter-open');assert.equal(await page.locator('#filter-dialog').evaluate(d=>d.open),true);await page.check('[name="category"][value="bowls"]');assert.equal(await page.locator('#filter-apply').textContent().then(s=>s.trim()),'Show 2 products');await page.click('#filter-apply');assert.equal(await page.locator('#shop-products .product-card').count(),2);await page.click('#filter-open');await page.keyboard.press('Escape');await page.waitForTimeout(100);assert.equal(await page.locator('#filter-dialog').evaluate(d=>d.open),false);assert.equal(await page.locator('body').evaluate(e=>e.classList.contains('is-locked')),false);
await page.setViewportSize({width:1440,height:1000});await page.locator('.shop-sidebar #filter-panel').waitFor({state:'attached'});assert.equal(await page.locator('.shop-sidebar #filter-panel').count(),1);await page.emulateMedia({reducedMotion:'reduce'});await page.click('.shop-sidebar [data-clear]');assert.equal(await page.locator('#shop-products .product-card').count(),12);
await fs.writeFile('review/shop-results.json',JSON.stringify({errors,failed,axe},null,2));console.log(JSON.stringify({errors,failed,axe},null,2));assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);assert.equal(axe.reduce((n,r)=>n+r.violations.length,0),0);await browser.close();console.log('PASS: combined filters, sorting, search, URL reload, bag/wishlist, shared cart, brands, 4 widths, mobile filter sheet, reduced motion.');
