import{chromium}from'/Users/rajan/Downloads/main portfolio/cinematic/node_modules/playwright/index.mjs';import assert from'node:assert/strict';import fs from'node:fs/promises';import AxeBuilder from'/tmp/urban-shisha-audits/node_modules/@axe-core/playwright/dist/index.mjs';
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();const errors=[],failed=[],axe=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failed.push(r.url());});await page.goto('http://127.0.0.1:8091/wholesale.html',{waitUntil:'networkidle'});await page.locator('#age-dialog').waitFor({state:'visible'});await page.keyboard.press('Escape');await page.waitForTimeout(100);assert.equal(await page.locator('#age-dialog').evaluate(d=>d.open),true);await page.click('#age-accept');await page.waitForTimeout(800);
await page.evaluate(()=>localStorage.setItem('urban-preview-cart',JSON.stringify([{id:'studio-black',qty:2}])));const retail=await page.evaluate(()=>localStorage.getItem('urban-preview-cart'));
assert.equal(await page.locator('.ws-product-card').count(),4);await page.click('[data-bulk-add="studio-black"]');await page.fill('[data-qty="studio-black"]','25');await page.locator('[data-qty="studio-black"]').press('Tab');assert.match(await page.locator('#ws-enquiry-count').textContent(),/25 units/);await page.click('#ws-categories [data-category="charcoal"]');await page.click('[data-bulk-add="coconut-charcoal"]');await page.fill('[data-qty="coconut-charcoal"]','100');await page.locator('[data-qty="coconut-charcoal"]').press('Tab');assert.match(await page.locator('#ws-enquiry-count').textContent(),/125 units/);assert.equal(await page.evaluate(()=>localStorage.getItem('urban-preview-cart')),retail);
await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('.ws-line').count(),2);assert.match(await page.locator('#ws-form-count').textContent(),/125 units/);await page.locator('#ws-quote-form button[type="submit"]').click();assert.equal(await page.locator('#ws-name').getAttribute('aria-invalid'),'true');assert.equal(await page.evaluate(()=>document.activeElement.id),'ws-name');
const values={name:'Test Buyer',business:'Test Business',city:'Delhi',pin:'110001',email:'buyer@example.com',phone:'9876543210'};for(const[k,v]of Object.entries(values))await page.fill('#ws-'+k,v);await page.selectOption('#ws-type','Retail store');await page.locator('#ws-quote-form button[type="submit"]').click();assert.equal(await page.locator('#ws-review-dialog').evaluate(d=>d.open),true);assert.match(await page.locator('#ws-prepared-message').inputValue(),/COCOYAYA Brando — 25 units/);assert.match(await page.locator('#ws-prepared-message').inputValue(),/100 units/);assert.equal(await page.locator('#ws-send-whatsapp').isVisible(),false);assert.equal(await page.evaluate(()=>Object.values(localStorage).some(v=>v.includes('buyer@example.com'))),false);await page.keyboard.press('Escape');await page.waitForTimeout(100);assert.equal(await page.locator('body').evaluate(e=>e.classList.contains('is-locked')),false);
for(const width of[1440,1024,768,390]){await page.setViewportSize({width,height:1000});await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(350);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);await page.screenshot({path:`review/wholesale-${width}.png`});const report=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();axe.push({width,violations:report.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))});await page.locator('#business-details').scrollIntoViewIfNeeded();await page.waitForTimeout(300);await page.screenshot({path:`review/wholesale-form-${width}.png`});}
await page.locator('#enquiry-list').scrollIntoViewIfNeeded();await page.click('[data-remove="coconut-charcoal"]');assert.equal(await page.locator('.ws-line').count(),1);await page.click('#ws-clear-list');assert.equal(await page.locator('#ws-enquiry-empty').isVisible(),true);await page.locator('#ws-quote-form button[type="submit"]').click();assert.equal(await page.locator('#ws-selection-error').isVisible(),true);assert.equal(await page.evaluate(()=>localStorage.getItem('urban-preview-cart')),retail);
await page.goto('http://127.0.0.1:8091/index.html',{waitUntil:'networkidle'});assert.equal(await page.locator('.desktop-nav a[href="wholesale.html"]').count(),1);assert.equal(await page.locator('#builder').count(),1);
await page.route('**/gsap.min.js',r=>r.abort());await page.goto('http://127.0.0.1:8091/wholesale.html',{waitUntil:'networkidle'});await page.locator('[data-bulk-add="studio-black"]').click();assert.equal(await page.locator('.ws-line').count(),1);await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#ws-categories [data-category="all"]').click();assert.equal(await page.locator('.ws-product-card').count(),12);
const report={errors,failed,axe,checks:'separate persisted enquiry, quantities, category filters, form errors, review, no personal storage, retail preserved, 4 widths, navigation, GSAP fallback'};await fs.writeFile('review/wholesale-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);assert.equal(axe.reduce((n,r)=>n+r.violations.length,0),0);await browser.close();
